[package]
name = "game-of-life"
version = "0.1.0"
edition = "2021"
authors = ["Vincent Hiribarren"]
description = "Toy project to test the Conway's Game of Life with Rust and Bevy"
license = "MIT"

[dependencies]
bevy = "0.11.2"
bevy_egui = "0.21.0"
